export enum AuditAction {
    // Inventory-Critical Actions
    GRN_POSTED = 'GRN_POSTED',
    ISSUE_POSTED = 'ISSUE_POSTED',
    TRANSFER_POSTED = 'TRANSFER_POSTED',
    ADJUSTMENT_CREATED = 'ADJUSTMENT_CREATED',
    OPENING_STOCK_SET = 'OPENING_STOCK_SET',

    // Warehouse Lifecycle
    WAREHOUSE_CREATED = 'WAREHOUSE_CREATED',
    WAREHOUSE_ARCHIVED = 'WAREHOUSE_ARCHIVED',
    WAREHOUSE_REACTIVATED = 'WAREHOUSE_REACTIVATED',

    // User & Access Management
    USER_INVITED = 'USER_INVITED',
    USER_REMOVED = 'USER_REMOVED',
    ROLE_CHANGED = 'ROLE_CHANGED',
    USER_ASSIGNED_TO_WAREHOUSE = 'USER_ASSIGNED_TO_WAREHOUSE',
    USER_REMOVED_FROM_WAREHOUSE = 'USER_REMOVED_FROM_WAREHOUSE',

    // Bulk & Admin Operations
    BULK_IMPORT_STARTED = 'BULK_IMPORT_STARTED',
    BULK_IMPORT_COMPLETED = 'BULK_IMPORT_COMPLETED',
    BARCODE_LABELS_GENERATED = 'BARCODE_LABELS_GENERATED',

    // Expiry & Automation
    EXPIRY_SCAN_RUN = 'EXPIRY_SCAN_RUN',
    LOT_EXPIRED = 'LOT_EXPIRED',
    LOT_EXPIRING_SOON = 'LOT_EXPIRING_SOON',
}

export enum AuditEntityType {
    WAREHOUSE = 'WAREHOUSE',
    GRN = 'GRN',
    ISSUE = 'ISSUE',
    TRANSFER = 'TRANSFER',
    ADJUSTMENT = 'ADJUSTMENT',
    OPENING_STOCK = 'OPENING_STOCK',
    USER = 'USER',
    PRODUCT = 'PRODUCT',
    STOCK_LOT = 'STOCK_LOT',
    BULK_IMPORT = 'BULK_IMPORT',
    BARCODE = 'BARCODE',
}
